% -*- Erlang -*-
{'refactorerl/src/*', [{outdir, "refactorerl/ebin"},
                       {i, "refactorerl/include"}]}.
{'clustering/src/*', [{outdir, "clustering/ebin"},
                      {i, "clustering/include"}]}.
